const axios = require('axios');

const API_URL = 'http://localhost:3000/api/track';

async function testSimulatorPayload() {
    console.log("🚀 Testing Simulator Logic Payload...");

    // Simulate the data generated by the updated page.js
    const deviceId = "SIM_TEST_MANUAL";
    const status = "1"; // Stolen
    const lat = 13.9999;
    const lng = 100.9999;
    const timestamp = Math.floor(Date.now() / 1000);

    // Exact format from page.js: `${deviceId},${point.status} ${point.lat}, ${point.lng}, ${timestamp}`
    const payload = `${deviceId},${status} ${lat}, ${lng}, ${timestamp}`;

    console.log("Generated Payload:", payload);

    try {
        const response = await axios.post(API_URL, payload, {
            headers: { 'Content-Type': 'text/plain' }
        });
        console.log("✅ Server Response:", response.data);
    } catch (e) {
        console.error("❌ Request Failed:", e.message);
        if (e.response) console.error("Server Error Data:", e.response.data);
    }
}

testSimulatorPayload();
